services:
  app:
    build:
      context: .
    image: valet-ai-backend:latest
    container_name: valet-ai-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: valet-ai-postgres
    environment:
      POSTGRES_DB: valet_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # localのpostgresとの競合を防ぐため

volumes:
  db-data:
