spring:
  datasource:
    url: jdbc:postgresql://db:5432/nippogen
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  application:
    github:
      api:
        base-url: https://api.github.com
        token: ${GITHUB_TOKEN}
        timeout: 30s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
